### ISSUE TITLE
SizeChunker: 0 size chunk occurring in regular intervals

### ISSUE THREAD

**Issue by objelke** [Olegas/node-chunking-streams#7]
Similar to the previous issue (#6)

In the example below, 0 size packets are handed to the "data" event at id's 8,16,24,32,,,,,,,,

Not formally incorrect, understanding the interface, but at the very minimum, time/resource wasting.

Example:

```javascript
var input = fs.createReadStream(fname);
var chunker = new chunkers.SizeChunker({
        chunkSize: 8192,
        flushTail: true
});
    
chunker.on('data', function (chunk) {
    // we're getting null length packets ever so often
    if (chunk.data.length) {
        // further logic goes here....
    }
});
    
input.pipe(chunker);

```

(addendum: that put aside, great contribution to the community, thanks!)

**Comment by Olegas** [comment]
Published as 0.0.8
